servo: Merge #13935 - Switch glutin to use the crates.io version of osmesa-sys to remove a duplicate (from fabricedesre:duplicate-osmesa-sys); r=emilio
<!-- Please describe your changes on the following line: -->
This removes the use of a git reference to osmesa-sys in glutin, to use the crates.io one with the same version that is already used in servo:
fabrice@fabrice-ThinkPad-X260:~/dev/servo/components/servo$ cargo tree -i -p osmesa-sys
error: There are multiple `osmesa-sys` packages in your project, and the specification `osmesa-sys` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  https://github.com/daggerbot/osmesa-rs#osmesa-sys:0.1.2
  https://github.com/rust-lang/crates.io-index#osmesa-sys:0.1.2

---
<!-- Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data: -->
- [X ] `./mach build -d` does not report any errors
- [X ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

<!-- Either: -->
- [ ] There are tests for these changes OR
- [X ] These changes do not require tests because this is building the same code from a different source.

<!-- Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process. -->

Source-Repo: https://github.com/servo/servo
Source-Revision: 1e7434f05c0ab895ce5571da163234868545ceda