Backed out changeset 7819e11aa46f, bug 592052 because of Mac OS X build bustage:
Undefined symbols:
  "_NSGetModule", referenced from:
     -exported_symbols_list command line option
ld: symbol(s) not found